from pyChatGPT import ChatGPT

# `__Secure-next-auth.session-token` cookie from https://chat.openai.com/chat
session_token = 'eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..36_bpmEVgPvLmdhX.id_7q59y88W5Rm6D_76IgXgWqpdDc0IGPvpk8UtPeI46zTNoboY7z4Mnz1l_XamY-CKwF8_LR-ONZt74UBKFH7x26eyXNDAtdq6XSlNQLhCZH0eUlriSZeitgAQamOUZDQEtZfWP_Mu71FPiq_lO-lUCvvHWXII8cMshfqQMx-GGzSTxdj6IBgImN9ciJy18vu_9aff4KpLqujdEgBKDZtII27q0Pkn4F4VEJApguDWDqcQgFregxATFk0y0xmcNuuMF-Te5E_MU2D5m5ecZuM3mR_bST_jHSYy59m6cnQj7C3efkmkIqkkYiERu7zPlFKlCdDkKSHOCD-SdOqkO584MjAPzmapl_dC3Fg7zOMEWBExZNBsHIUAoTv-AxSn3JCrvHIDt-Rrbrdxbq-ASB819-uoDYPDliOLY_Mdha0N8qGURbxPNWTZuZAAKAK1agSKhSdn3LoJ31Bf_erKou4s7q4USC5Laap-tmP9uz3xcfEtjWSJFsQ2JvpBoPwI9JBWgGLWOKNfCHCABT_YL9NrlnQJfu34PYeUjEHBNZVxTraft9KkjKCZ4UdmZfpXqN9Z1bfcGGh-g4i_MPuetvuBVf9VCzH7UFZg5BjY_OroL5nU8ljlHXCxuycgFt7_pqZDxfLCg2Lj-yKph5KuTl8TM4zzST0HZK6pYqipQv2-HcXawQz0kKjDlLMmKM2RY9UW-HmTGRA5kiLz47dsnDO6me6VgeMUr_drvhVtJLPCTO-SIpvgTK_RU4rMR1gwgqHugP0R8IweE7LgMaIDnCO0vpIsp1vrvCbzhW98C9JJJnwBHBa2RgB4LLeR5rIv7JVK_7ta2iqUm8BLLw3zeVPRXXzLgi4mCz6qDDHVRmid_xNGmCqKZX3ufFtIyBOeAp-xw8diaVXiA1R8kWQld5Y3MZOgXHEp1VfH23oBNarC_Xom05XB-A9UJIV10uJdX8MjZNBr0GjdvQfuJFK2E0wPrLhv9fHpUN2yHSM_sLlKba-p8uQ-G22iN9hecyR7opHoiccf8_hMAwefJrVjFH7O6RMhHb8NEXaxzfWZZm7KefF8jlUo0Mmv7Dtx-uUh-qLQpVA0PK3vbEis3i0lvC98PN8x1ATScMb8fkaintq1bC-IW3qJPuEko9RgFJu0W9ZSUFalOXKiZWIlVb0JXFMxLZ3h2rHLl0oNmOGAsPrZgAQXdF85tYG4HsDITX3t7zfgEYWpgHVj2tZFdn8yTD65Rm-Ys5DsSASZaqLgXIm7OLBruJotLPQQa_S5Qnq6sYpGr-MQ3wmoqYPeXBCoEF29KUxUxOqyIm51iLf8dHHmEsU1vTiQT_YTnDdnGP7wsX33q7Iu8UajLmOHAErFottV1NN-iK0ho82PC1zwXP1nOLcj5LbmGRUH3X6Ir8Dafp13lZInxFA5XPNQH7-jR2ftTor5_-fGNewADDcZ6UiBg5XD5QlQt3zCmOAnXDssB6Fz61IOycHvFhTnmvCtYUNz6sE7mLUmKq4iRqRDPd7BMvrgfqAn0oN0WCBg_4iC_TbDQApqaxazROD9c_EGpABzlMI8MbWRd4T2KqTYO4QF_vCJQ368IIswVVgV7Q7n6qkxnNWOhussHmfRjj7L7pR03IlN2XV_v4rBbgei7T3sO_fhK0l0AD_cPiFvSB7NzXRTQnLYEVNi1EeyjDAHF6Ka0ZckgjA3zLzEm5Kvr8rnDZfOdKggT6YksQb1ktYVNGgaVEcixwZp8pQqc1tkP-fG823moI85kyKMxjEsEsPifBu68iOzTZ3oFjxEl-kolgJpPxOm5KvZsIs-2FYXr5sRU0dIRjaJTejyo3QWSllgfJ2xpBjr_18SvWa8mKjvAziKPeOunhFXEyaV3GA2kV_XIy0gsNwT3d7pET_coCTXUVyooE3IEMR7xIcYCU-tSvLzG4BsULXOApK_2P8Bnic9Lw_HT0cAKBCVxNH3Bqm1YkjWPnCjBmSIZUcbbTvR_oL_STIaCXSGMn_Bt_i9UFk2zcjQv_oYhK7W2M1V6rg3MDQM21SrE7NSU7USn1jGAxYchNaCSb0cmVa_kWynPYyUj4FQyyX6MGVMvNAXV00g8yG3oeCEj3hPeSRMzxpOTmUVM-cno-FR2fD7nRfZ0mxMZl6kEI27tdnHz-CVrHhqOUjYuiYJfypowmBUIT-MYFB8mdqrvOhzw4gG9FSkQ1SRC-Z97sU_z_sFBTUnlf72v-nW4istEOeZJCCQeAzwLnmf_2Dd4k_GY7D3LqIvTNRzXLuUBf1q2YRQMQw.lq7F5ty94tfbwa05o-m-UA'  

# api = ChatGPT(session_token)  # auth with session token
# api = ChatGPT(session_token, conversation_id='some-random-uuid')  # specify conversation id
# api = ChatGPT(session_token, proxy='https://proxy.example.com:8080')  # specify proxy
# api = ChatGPT(session_token, chrome_args=['--window-size=1920,768'])  # specify chrome args
# api = ChatGPT(session_token, moderation=False)  # disable moderation
# api = ChatGPT(session_token, verbose=True)  # verbose mode (print debug messages)

# auth with google login
api = ChatGPT(auth_type='google', email='arangapur@hawk.iit.edu', password='Hulk-bhai123')
# auth with microsoft login
# api = ChatGPT(auth_type='microsoft', email='example@gmail.com', password='password')
# # auth with openai login (captcha solving using speech-to-text engine)
# api = ChatGPT(auth_type='openai', email='example@gmail.com', password='password')
# auth with openai login (manual captcha solving)
# api = ChatGPT(
#     auth_type='openai', captcha_solver=None,
#     email='example@gmail.com', password='password'
# )
# auth with openai login (2captcha for captcha solving)
api = ChatGPT(
    auth_type='openai', captcha_solver='2captcha', solver_apikey='abc',
    email='example@gmail.com', password='password'
)
# reuse cookies generated by successful login before login,
# if `login_cookies_path` does not exist, it will process logining  with `auth_type`, and save cookies to `login_cookies_path`
# only works when `auth_type` is `openai` or `google`
# api = ChatGPT(auth_type='openai', email='example@xxx.com', password='password',
#     login_cookies_path='your_cookies_path',
# )

resp = api.send_message('Hello, world!')
print(resp['message'])

# api.reset_conversation()  # reset the conversation
# api.clear_conversations()  # clear all conversations
# api.refresh_chat_page()  # refresh the chat page